---
- name: "ensure presence of default group '{{ default_group_name }}'"
  ansible.builtin.group:
    name: "{{ default_group_name }}"
    gid: "{{ default_group_gid }}"

- name: ensure common sshd settings applied
  ansible.builtin.import_tasks: sshd.yml

- name: OS-specific vars and packages
  tags:
    - packages
  block:

  - name: include OS-specific variables
    ansible.builtin.include_vars: "{{ lookup( 'ansible.builtin.first_found', params ) }}"
    vars:
      params:
        files:
          - "os-{{ ansible_distribution }}.yml"
          - "os-{{ ansible_os_family }}.yml"
          - "main.yml"
        paths:
          - "vars"

- name: "{{ ansible_distribution|lower }}-specific bootstrap tasks"
  ansible.builtin.include_tasks: "os-{{ ansible_distribution|lower }}.yml"
