---
- name: ensure presence of default group "{{ default_group.name }}"
  group:
    name: "{{ default_group.name }}"
    gid: "{{ default_group.gid }}"

- name: ensure timezone is set to utc
  timezone:
    name: UTC

- name: "{{ ansible_os_family|lower }}-specific bootstrap tasks"
  include: 'os-{{ ansible_os_family|lower }}.yml'

- import_tasks: sshd.yml
