---
- name: ensure presence of default group "{{ default_group.name }}"
  group:
    name: "{{ default_group }}"
    gid: "{{ default_group_gid }}"

- name: ensure timezone is set to utc
  timezone:
    name: Etc/UTC

- name: "{{ ansible_distribution|lower }}-specific bootstrap tasks"
  import_tasks: "os-{{ ansible_distribution|lower }}.yml"

- name: ensure sshd settings applied
  import_tasks: sshd.yml
