---
- name: ensure presence of default group "{{ default_group }}"
  ansible.builtin.group:
    name: "{{ default_group }}"
    gid: "{{ default_group_gid }}"

- name: ensure timezone is set to utc
  community.general.timezone:
    name: Etc/UTC

- name: "{{ ansible_distribution|lower }}-specific bootstrap tasks"
  ansible.builtin.include: "os-{{ ansible_distribution|lower }}.yml"

- name: ensure sshd settings applied
  ansible.builtin.import_tasks: sshd.yml
