---
- name: "({{ ansible_os_family|lower }}-specific) ensure presence of common {{ ansible_os_family|lower }} packages"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - bash-completion
    - ca-certificates
    - curl
    - fail2ban
    - git
    - python3-pip
    - software-properties-common
    - ufw
    - vim
  notify:
    - start fail2ban
    - start ufw

- name: "({{ ansible_os_family|lower }}-specific) get rid of annoying help text in `/etc/update-motd.d/`"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/update-motd.d/10-help-text
    - /etc/update-motd.d/51-cloudguest

- name: "({{ ansible_os_family|lower }}-specific) ensure ufw is enabled and default outgoing policy is 'allow'"
  ufw:
    state: enabled
    direction: outgoing
    policy: allow

- name: "({{ ansible_os_family|lower }}-specific) ensure ufw is enabled and default incoming policy is 'deny'"
  ufw:
    state: enabled
    direction: incoming
    policy: deny

- name: "({{ ansible_os_family|lower }}-specific) ensure ssh port is allowed through ufw"
  ufw:
    rule: allow
    port: "{{ default_ssh_port }}"
    log: yes

- name: "({{ ansible_os_family|lower }}-specific) ensure fail2ban jail.local is present"
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: 0600
    owner: root
    group: root
  notify: restart fail2ban
