---
- name: package tasks
  tags:
    - packages
  block:

    - name: ensure presence of commonly-used packages selected for install
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ packages_installed }}"
      notify:
        - start firewalld

    - name: ensure absence of packages selected for removal
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ packages_removed }}"