---
- name: "({{ ansible_distribusion|lower }}-specific) check if epel repo is already configured"
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: "({{ ansible_distribusion|lower }}-specific) ensure presence of epel repo"
  package:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: 'result.rc == 0'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: "({{ ansible_distribusion|lower }}-specific) ensure presence of epel gpg key"
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"
