---
- name: "({{ ansible_os_family|lower }}-specific) ensure presence of common {{ ansible_os_family|lower }} packages"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bzip2
    - curl
    - perl
    - tar
