---
- name: "({{ ansible_distribution|lower }}-specific) ensure presence of common {{ ansible_distribution|lower }} packages"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-file                   # list contents of packages
    - apt-transport-https        # HTTPS support for apt tools
    - bash-completion            # for peace of mind when using terminal
    - ca-certificates            # certificate authority data
    - curl                       # command line HTTP client
    - fail2ban                   # ban denial-of-service network traffic
    - git                        # revision control tool
    - python3-pip                # necessary for ansible?
    - python3-venv               # for python virtual environments
    - software-properties-common # provides `add-apt-repository`
    - tasksel                    # quickly install common package collections
    - ufw                        # uncomplicated firewall
    - whois                      # provides `mkpasswd`
    - vim                        # visual text editor
    - zsh                        # shell of choice
  notify:
    - start fail2ban
    - start ufw

- name: "({{ ansible_distribution|lower }}-specific) get rid of annoying help text in `/etc/update-motd.d/`"
  file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  with_items:
    - 10-help-text
    - 50-motd-news
    - 51-cloudguest

- name: "({{ ansible_distribution|lower }}-specific) ensure ufw is enabled and default outgoing policy is 'allow'"
  ufw:
    state: enabled
    direction: outgoing
    policy: allow

- name: "({{ ansible_distribution|lower }}-specific) ensure ufw is enabled and default incoming policy is 'deny'"
  ufw:
    state: enabled
    direction: incoming
    policy: deny

- name: "({{ ansible_distribution|lower }}-specific) ensure ssh port is allowed through ufw"
  ufw:
    rule: allow
    port: "{{ default_ssh_port }}"
    log: yes

- name: "({{ ansible_distribution|lower }}-specific) ensure fail2ban jail.local is present"
  copy:
    src: jail.local.txt
    dest: /etc/fail2ban/jail.local
    mode: 0600
    owner: root
    group: root
  notify: restart fail2ban
