---
- name: start fail2ban
  ansible.builtin.systemd:
    name: fail2ban.service
    state: started
    enabled: yes

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban.service
    state: restarted

- name: start firewalld
  ansible.builtin.systemd:
    name: firewalld.service
    state: started

- name: start ufw
  ansible.builtin.systemd:
    name: ufw.service
    state: started
    enabled: yes

- name: restart ufw
  ansible.builtin.systemd:
    name: ufw.service
    state: restarted

- name: reload ufw
  community.general.ufw:
    state: reloaded
